Repository fine-ants/frontend, pull requests merged in 2023-11, with the labels that each got.

#1 [chore] Issue, commit message 및 PR template 추가
  .github/.commit_template.txt
  .github/ISSUE_TEMPLATE/기능-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#4 [feat] Watchlist 라이브러리 변경 및 종목 추가,삭제 기능 구현
  package-lock.json
  package.json
  src/api/watchlist/index.ts
  src/api/watchlist/queries/queryKeys.ts
  src/api/watchlist/queries/useWatchlistItemAddMutation.ts
  src/api/watchlist/queries/useWatchlistItemDeleteMutation.ts
  src/api/watchlist/queries/useWatchlistQuery.ts
  src/components/Watchlist/Watchlist.tsx
  src/components/Watchlist/WatchlistItem.tsx
  src/components/Watchlist/WatchlistItemAddModal.tsx
  src/components/Watchlist/WatchlistItemDeleteAlert.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/mocks/data/watchlistData.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/watchlistHandlers.ts
  src/pages/BasePage.tsx
  src/pages/WatchlistPage.tsx
Labels: design, feat, refactor

#7 modal 컴포넌트 명칭 명확한 명칭으로 변경
  src/api/watchlist/queries/useWatchlistItemAddMutation.ts
  src/api/watchlist/queries/useWatchlistItemDeleteMutation.ts
  src/components/BaseDialog.tsx
  src/components/ConfirmAlert.tsx
  src/components/Portfolio/PortfolioDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingPurchaseAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Watchlist/Watchlist.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/Watchlist/WatchlistItemDeleteAlert.tsx
  src/components/common/Header.tsx
  src/pages/PortfolioPage.tsx
Labels: rename

#10 [feat] 대쉬보드 현 디자인 시안에 맞게 UI 적용
  src/assets/icons/facebook.svg
  src/assets/icons/instagram.svg
  src/assets/icons/linkedin.svg
  src/assets/icons/notification-hover.svg
  src/assets/icons/notification.svg
  src/assets/icons/search.svg
  src/assets/icons/settings-hover.svg
  src/assets/icons/settings.svg
  src/assets/icons/x.svg
  src/assets/icons/youtube.svg
  src/assets/images/profileImage.png
  src/components/Dashboard/TotalValuationLineChart.tsx
  src/components/Dashboard/ValuationOverview.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/TradingViewWidgets/TVTickerTape.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/UserControls.tsx
  src/index.css
  src/mocks/data/portfolioData.ts
  src/pages/BasePage.tsx
  src/pages/DashboardPage.tsx
  src/pages/IndicesPage.tsx
  src/pages/LandingPage.tsx
  src/pages/PortfolioPage.tsx
  src/pages/ProfilePage/MyProfilePage.tsx
  src/pages/ProfilePage/PortfoliosPage.tsx
  src/pages/StockPage.tsx
  src/pages/WatchlistPage.tsx
  src/router/router.tsx
Labels: design, feat

#11 [refactor] portfolio dialog
  src/components/Portfolio/PortfolioDialog.tsx
  src/utils/calculations.ts
Labels: bug fix, refactor

#13 [feat] 디자인 시스템 구축 및 UI 최신화
  src/App.tsx
  src/assets/images/kakao_logo.jpeg
  src/assets/images/naver_logo.png
  src/components/Dashboard/PortfolioPieChart.tsx
  src/components/Dashboard/TimeRangeButton.tsx
  src/components/Dashboard/TotalValuationLineChart.tsx
  src/components/Dashboard/ValuationOverview.tsx
  src/components/Portfolio/HoldingsPieChart.tsx
  src/components/Portfolio/SectorBar.tsx
  src/components/auth/KakaoSignInButton.tsx
  src/components/auth/NaverSignInButton.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/PieChart/Legend.tsx
  src/components/common/PieChart/LegendItem.tsx
  src/components/common/PieChart/PortfolioPieChart.tsx
  src/components/common/PieChart/RechartPieChart.tsx
  src/components/common/UserControls.tsx
  src/mocks/data/portfolioData.ts
  src/pages/BasePage.tsx
  src/pages/DashboardPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/MainSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/pages/SignUpPage/subPages/SubPage.tsx
  src/styles/chartColorPalette.ts
  src/styles/designSystem.ts
Labels: design, feat

#18 custom Toast 추가
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/components/hooks/Toast.tsx
Labels: feat, refactor

#23 [refactor] useFunnel hook 구현
  __tests__/hooks/useFunnel.test.tsx
  src/hooks/useFunnel.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/MainSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/pages/SignUpPage/subPages/SubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
Labels: refactor

#29 [refactor] 전반적인 Refactor
  src/api/portfolio/index.ts
  src/api/portfolio/queries/queryKeys.ts
  src/api/portfolio/queries/usePortfolioHoldingChartsQuery.ts
  src/api/portfolio/queries/usePortfolioListQuery.ts
  src/api/portfolio/types.ts
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Dashboard/DashboardPortfolioWeight.tsx
  src/components/Dashboard/DashboardTotalValuationTrend.tsx
  src/components/Dashboard/PortfolioWeightPieChart/EmptyPortfolioMessage.tsx
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChart.tsx
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/components/Portfolio/Charts/ChartsPanel.tsx
  src/components/Portfolio/Charts/DividendBarChart.tsx
  src/components/Portfolio/Charts/HoldingsPieChart.tsx
  src/components/Portfolio/Charts/SectorBar.tsx
  src/components/Portfolio/Charts/skeletons/ChartsPanelSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/DividendBarChartSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/HoldingsPieChartSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/SectorBarSkeleton.tsx
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Watchlist/Watchlist.tsx
  src/components/common/Header.tsx
  src/components/common/PieChart/Legend.tsx
  src/components/common/PieChart/PieChartLegend.tsx
  src/components/common/PieChart/PieChartLegendItem.tsx
  src/components/common/PieChart/skeletons/PieChartLegendSkeleton.tsx
  src/components/common/PieChart/skeletons/PieChartSkeleton.tsx
  src/components/common/UserControls.tsx
  src/mocks/data/dashboardData.ts
  src/mocks/data/portfolioData.ts
  src/mocks/handlers/portfolioHandlers.ts
  src/pages/BasePage.tsx
  src/pages/DashboardPage.tsx
  src/pages/MyProfilePage.tsx
  src/pages/Portfolio/PortfolioPage.tsx
  src/pages/Portfolio/PortfoliosListPage.tsx
  src/pages/ProfilePage/MyProfilePage.tsx
  src/pages/ProfilePage/PortfoliosPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/WatchlistPage.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: design, feat, refactor

#32 [feat] 공통 컴포넌트 구현
  __tests__/utils/calculations.test.ts
  src/assets/icons/ic_down.svg
  src/assets/icons/ic_none.svg
  src/assets/icons/ic_up.svg
  src/components/Dashboard/DashboardOverview.tsx
  src/components/common/Badges/CounterBadge.tsx
  src/components/common/Badges/LabelBadge.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/TextButton.tsx
  src/components/common/UserControls.tsx
  src/styles/designSystem.ts
Labels: design, feat
