Repository fine-ants/frontend, pull requests merged in 2023-12, with the labels that each got.

#37 dropdown 리팩터링
  src/components/common/Header.tsx
  src/components/common/PortfoliosDropdown.tsx
  src/components/hooks/useDropdown.tsx
Labels: feat, refactor

#45 대시보드 suspend&error boundary 적용
  package-lock.json
  package.json
  src/api/dashboard/queries/useDashboardLineChartQuery.tsx
  src/api/dashboard/queries/useDashboardOverviewQuery.tsx
  src/api/dashboard/queries/useDashboardPieChartQuery.tsx
  src/components/Dashboard/errorFallback/ChartErrorFallback.tsx
  src/components/Dashboard/errorFallback/OverviewErrorFallback.tsx
  src/components/Dashboard/skeletons/DashboardLineChartSkeleton.tsx
  src/components/Dashboard/skeletons/DashboardOverviewSkeleton.tsx
  src/components/Dashboard/skeletons/DashboardPieChartSkeleton.tsx
  src/components/Dashboard/skeletons/PieChartLegendSkeleton.tsx
  src/components/Dashboard/skeletons/PieChartSkeleton.tsx
  src/components/common/AsyncBoundary.tsx
  src/components/common/ErrorFallbackContent.tsx
  src/pages/DashboardPage.tsx
Labels: chore, feat, refactor

#42 useSSE 구현
  package-lock.json
  package.json
  src/api/hooks/useSSE.tsx
  src/pages/Portfolio/PortfolioPage.tsx
Labels: feat

#46 [refactor] 검색바 debounce 적용 및 context 제거
  src/api/portfolio/queries/usePortfolioListQuery.ts
  src/api/stock/index.ts
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/common/Header.tsx
  src/components/hooks/useInputDebounce.ts
  src/pages/SignInPage.tsx
Labels: refactor

#48 auth UI 작업
  src/assets/icons/arrow.svg
  src/assets/images/google_logo.svg
  src/assets/images/kakao_logo.svg
  src/assets/images/naver_logo.svg
  src/components/auth/AuthInput.tsx
  src/components/auth/AuthOnPrevButton.tsx
  src/components/auth/AuthPageCommon.tsx
  src/components/auth/AuthPasswordInput.tsx
  src/components/auth/BaseSignInButton.tsx
  src/components/auth/GoogleSignInButton.tsx
  src/components/auth/KakaoSignInButton.tsx
  src/components/auth/NaverSignInButton.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/hooks/useDebounce.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/MainSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
  src/pages/SignUpPage/subPages/SubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
Labels: design, feat, refactor

#53 [feat] PortfolioListPage 및 Root Level ErrorBoundary 적용
  src/components/Portfolio/PortfolioList/errorFallback/PortfolioListTableErrorFallback.tsx
  src/components/common/AsyncBoundary.tsx
  src/mocks/handlers/portfolioHandlers.ts
  src/pages/DashboardPage.tsx
  src/pages/GlobalErrorPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Portfolio/PortfolioListPage.tsx
  src/router/router.tsx
Labels: feat

#59 textfield 구현
  src/components/auth/AuthInput.tsx
  src/components/auth/AuthPasswordInput.tsx
  src/components/common/TextField/BaseTextField.tsx
  src/components/common/TextField/ErrorText.tsx
  src/components/common/TextField/PasswordTextField.tsx
  src/components/common/TextField/TextField.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
Labels: feat, refactor, rename

#60 [refactor] @fineants/demolition package 적용
  .husky/pre-commit
  __tests__/hooks/useFunnel.test.tsx
  __tests__/utils/authInputValidators.test.ts
  __tests__/utils/calculations.test.ts
  __tests__/utils/date.test.ts
  package-lock.json
  package.json
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/hooks/useImageInput.tsx
  src/components/hooks/useInputDebounce.ts
  src/components/hooks/useText.tsx
  src/hooks/useDebounce.tsx
  src/hooks/useFunnel.tsx
  src/pages/MyProfilePage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
  src/utils/authInputValidators.ts
Labels: chore, refactor

#63 [fix] OIDC Window Popup 바로 닫힘 현상 해결
  src/api/auth/index.ts
  src/api/auth/queries/useOAuthSignInMutation.ts
  src/components/auth/GoogleSignInButton.tsx
  src/components/auth/KakaoSignInButton.tsx
  src/components/auth/NaverSignInButton.tsx
  src/pages/SignInLoadingPage.tsx
  src/pages/SignInPage.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: bug fix, refactor

#65 #62 refactor: shouldClosePopUp 로직 수정
  src/pages/SignInPage.tsx
Labels: refactor

#67 [feat] Select, SelectOption 컴포넌트 구현 및 적용
  src/components/Portfolio/PortfolioList/PortfolioListTable.tsx
  src/components/common/Pagination/TablePagination.tsx
  src/components/common/Select/Select.tsx
  src/components/common/Select/SelectOption.tsx
  src/components/common/Select/index.ts
  src/main.tsx
Labels: feat

#69 [feat] 포트폴리오 상세페이지 기능 구현
  src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  src/api/portfolio/types.ts
  src/assets/icons/ic_add_16.svg
  src/assets/icons/ic_arrow-left.svg
  src/assets/icons/ic_ascending_16.svg
  src/assets/icons/ic_check_12.svg
  src/assets/icons/ic_check_16.svg
  src/assets/icons/ic_chevron-down_12.svg
  src/assets/icons/ic_chevron-down_16.svg
  src/assets/icons/ic_chevron-left_16.svg
  src/assets/icons/ic_chevron-right_16.svg
  src/assets/icons/ic_chevron-up_12.svg
  src/assets/icons/ic_chevron-up_16.svg
  src/assets/icons/ic_close-small_12.svg
  src/assets/icons/ic_descending_16.svg
  src/assets/icons/ic_down.svg
  src/assets/icons/ic_edit_16.svg
  src/assets/icons/ic_folder-add_16.svg
  src/assets/icons/ic_help_16.svg
  src/assets/icons/ic_indet_12.svg
  src/assets/icons/ic_indet_16.svg
  src/assets/icons/ic_none_12.svg
  src/assets/icons/ic_notification_16.svg
  src/assets/icons/ic_remove_16.svg
  src/assets/icons/ic_search.svg
  src/assets/icons/ic_up_12.svg
  src/assets/images/no_holdings_pie_chart.png
  src/assets/images/no_holdings_stock.png
  src/components/BaseDialog.tsx
  src/components/Dashboard/DashboardPortfolioWeight.tsx
  src/components/Portfolio/Charts/ChartsPanel.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarChart.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarTooltip.tsx
  src/components/Portfolio/Charts/Dividend/RoundedBarShape.tsx
  src/components/Portfolio/Charts/Pie/EmptyHoldingsPieChartImg.tsx
  src/components/Portfolio/Charts/Pie/PieChartContainer.tsx
  src/components/Portfolio/Charts/Sector/SectorBar.tsx
  src/components/Portfolio/Charts/Sector/SectorBarChartContainer.tsx
  src/components/Portfolio/Charts/Sector/SectorBarItem.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchItem.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Breadcrumb.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Header.tsx
  src/components/common/Icon.tsx
  src/components/hooks/useOutsideClick.tsx
  src/pages/Portfolio/PortfolioPage.tsx
  src/utils/removeWord.ts
Labels: design, feat, refactor

#72 icon component 리팩터링
  src/assets/icons/ic_favorite.svg
  src/assets/icons/normal-check.svg
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/common/Icon.tsx
  src/pages/Portfolio/PortfolioPage.tsx
  src/styles/designSystem.ts
Labels: refactor

#73 [feat] WatchlistPage 구현
  package-lock.json
  package.json
  src/api/watchlist/index.ts
  src/api/watchlist/queries/useWatchlistItemDeleteMutation.ts
  src/api/watchlist/queries/useWatchlistQuery.ts
  src/components/Watchlist/EmptyWatchlistTable.tsx
  src/components/Watchlist/Watchlist.tsx
  src/components/Watchlist/WatchlistItem.tsx
  src/components/Watchlist/WatchlistItemDeleteAlert.tsx
  src/components/Watchlist/WatchlistTable.tsx
  src/components/Watchlist/WatchlistTableBody.tsx
  src/components/Watchlist/WatchlistTableHead.tsx
  src/components/Watchlist/WatchlistTableRow.tsx
  src/components/Watchlist/WatchlistTableToolBar.tsx
  src/components/Watchlist/errorFallback/WatchlistTableErrorFallback.tsx
  src/components/Watchlist/skeletons/WatchlistTableSkeleton.tsx
  src/components/common/CustomTooltip.tsx
  src/components/common/Icon.tsx
  src/mocks/data/watchlistData.ts
  src/mocks/handlers/watchlistHandlers.ts
  src/pages/StockPage.tsx
  src/pages/WatchlistPage.tsx
  src/router/Routes.ts
Labels: feat

#75 [fix] TablePagination `rowsPerPageOptions`이 "All"일 때 sort 미적용 버그 해결
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTable.tsx
  src/components/Watchlist/WatchlistTable.tsx
  src/components/common/Pagination/TablePagination.tsx
Labels: bug fix

#78 [refactor] Social Login Buttons 추상화 및 Popup Permission 처리
  package-lock.json
  package.json
  src/components/auth/GoogleSignInButton.tsx
  src/components/auth/KakaoSignInButton.tsx
  src/components/auth/NaverSignInButton.tsx
  src/components/auth/SocialLoginButton.tsx
  src/constants/config.ts
  src/mocks/data/authData.ts
  src/pages/SignInPage.tsx
  src/pages/SignUpPage/subPages/MainSubPage.tsx
  src/router/router.tsx
  src/styles/designSystem.ts
Labels: refactor
