Repository fine-ants/frontend, pull requests merged in 2024-02, with the labels that each got.

#127 [refactor] 자잘한 수정사항들 적용
  src/api/portfolio/queries/usePortfolioEditMutation.ts
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/TradingViewWidgets/TVStockDetailWidget.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Header/Header.tsx
  src/pages/IndicesPage.tsx
  src/pages/StockPage.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: design, refactor

#133 [feat] FCM 토큰 삭제 기능
  src/api/fcm.ts
  src/api/notifications/index.ts
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/context/UserContext.tsx
  src/mocks/data/notifications/notificationSettingsData.ts
  src/mocks/handlers/notifications/notificationSettingsHandlers.ts
  src/utils/retryFn.ts
Labels: feat

#137 알림 관련 리팩터링
  src/api/fcm.ts
  src/api/notifications/types.ts
  src/components/common/Header/Notification/EmptyNotification.tsx
  src/components/common/Header/Notification/NotificationItem.tsx
  src/mocks/data/notifications/memberNotificationsData.ts
Labels: refactor

#140 [fix] PortfolioHoldingsTable 1px scroll 버그
  README.md
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/mocks/data/notifications/notificationSettingsData.ts
Labels: bug fix, design

#142 [refactor] portfolio page 리팩터링
  src/api/portfolio/index.ts
  src/api/portfolio/types.ts
  src/components/Portfolio/Charts/ChartsPanel.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/mocks/data/portfolioData.ts
  src/mocks/handlers/portfolioHandlers.ts
  src/utils/executeIfNumeric.ts
Labels: refactor
