Repository fine-ants/frontend, pull requests merged in 2024-04, with the labels that each got.

#177 [feat] Add target gain, max loss notification toggle buttons in portfolio page
  src/api/notifications/queries/usePortfolioNotificationSettingsMutation.ts
  src/api/portfolio/types.ts
  src/components/Portfolio/MainPanel.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/mocks/data/portfolioDetailsData.ts
  src/mocks/handlers/notifications/notificationSettingsHandlers.ts
  src/mocks/handlers/portfolioHandlers.ts
Labels: feat, refactor

#180 [fix] Remove unnecessary nullish coalescing operators
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
Labels: refactor

#179 [refactor] UI 및 포트폴리오 페이지 리팩터링
  src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingPurchaseAddMutation.ts
  src/api/portfolio/queries/usePortfoliosDeleteMutation.ts
  src/components/Portfolio/MainPanel.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/components/common/Legend/TallLegend.tsx
  src/components/common/Legend/TallLegendItem.tsx
Labels: refactor

#186 [feat] 종목 지정가 최대 5개 초과 등록 시도 시 토스트 발생 및 숫자 input 쉼표 적용
  src/api/notifications/queries/useStockTargetPriceAddMutation.tsx
  src/components/Dashboard/DashboardPortfolioWeight.tsx
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioList/EmptyPortfolioListTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Stock/StockTargetPriceForm.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx
  src/mocks/handlers/portfolioHandlers.ts
  src/utils/calculations.ts
  src/utils/excludeDelimiters.ts
  src/utils/executeIfNumeric.ts
Labels: feat, refactor

#188 [refactor] 개발 모드 시 FCM Service Worker 미작동 문제 해결
  .gitignore
  config/vitePlugins.ts
  package-lock.json
  package.json
  src/firebase-messaging-sw.js
  src/main.tsx
  vite.config.ts
Labels: refactor

#190 [refactor] StockPage AsyncBoundary 적용 및 UI 수정
  src/api/stock/queries/useStockPageQeury.ts
  src/components/Stock/StockDetails.tsx
  src/components/TradingViewWidgets/TVStockDetailWidget.tsx
  src/pages/StockPage.tsx
  src/pages/StockPage/StockPage.tsx
  src/router/router.tsx
Labels: refactor

#192 [refactor] 기타 수정
  src/components/NavBar.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarTooltip.tsx
  src/mocks/handlers/portfolioHandlers.ts
Labels: refactor

#194 [refactor] Read FCM SW file using node instead of rollup in fcmSwEnvPlugin
  config/vitePlugins.ts
  src/main.tsx
Labels: refactor

#196 [refactor] Organize and remove redundant query keys
  src/api/dashboard/queries/queryKeys.ts
  src/api/dashboard/queries/useDashboardLineChartQuery.tsx
  src/api/dashboard/queries/useDashboardOverviewQuery.tsx
  src/api/dashboard/queries/useDashboardPieChartQuery.tsx
  src/api/notifications/queries/queryKeys.ts
  src/api/notifications/queries/useAllStockPriceTargetsDeleteMutation.ts
  src/api/notifications/queries/useDeleteAllMemberNotificationsMutation.ts
  src/api/notifications/queries/useDeleteMemberNotificationsMutation.ts
  src/api/notifications/queries/useMemberNotificationsQuery.ts
  src/api/notifications/queries/usePortfolioNotificationSettingsMutation.ts
  src/api/notifications/queries/usePortfolioNotificationSettingsQuery.ts
  src/api/notifications/queries/useReadAllMemberNotificationsMutation.ts
  src/api/notifications/queries/useStockNotificationSettingsMutation.ts
  src/api/notifications/queries/useStockNotificationSettingsQuery.ts
  src/api/notifications/queries/useStockTargetPriceDeleteMutation.ts
  src/api/portfolio/queries/queryKeys.ts
  src/api/portfolio/queries/usePortfolioAddMutation.ts
  src/api/portfolio/queries/usePortfolioDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioEditMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingPurchaseAddMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingPurchaseDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioHoldingPurchaseEditMutation.ts
  src/api/portfolio/queries/usePortfolioListQuery.ts
  src/api/portfolio/queries/usePortfoliosDeleteMutation.ts
  src/api/stock/queries/queryKeys.ts
  src/api/stock/queries/useStockSearchQuery.ts
  src/api/watchlist/queries/queryKeys.ts
  src/api/watchlist/queries/useWatchlistHasStockQuery.tsx
  src/api/watchlist/queries/useWatchlistItemAddMutation.ts
  src/api/watchlist/queries/useWatchlistItemDeleteMutation.ts
  src/api/watchlist/queries/useWatchlistNameEditMutation.ts
  src/api/watchlist/queries/useWatchlistsAddMutation.ts
  src/api/watchlist/queries/useWatchlistsDeleteMutation.ts
  src/api/watchlist/queries/useWatchlistsQuery.ts
Labels: refactor

#199 [refactor] Use form tags to allow enter for submissions
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Watchlist/NewWatchlistDialog.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/Watchlist/WatchlistNameEditDialog.tsx
  src/components/common/Buttons/IconButton.tsx
  src/components/common/Icon.tsx
  src/components/common/Pagination/TablePagination.tsx
Labels: refactor

#201 [refactor] demolition 신규 유틸함수 적용
  package-lock.json
  package.json
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/components/Notification/StockNotificationList/StockNotificationLotsTable/StockNotificationLotRow.tsx
  src/components/Notification/StockNotificationList/StockNotificationRow.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarTooltip.tsx
  src/components/Portfolio/Charts/Pie/HoldingsPieChart.tsx
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/Stock/StockDetails.tsx
  src/components/Stock/StockTargetPriceForm.tsx
  src/components/Stock/TargetPriceAlertDropdown/TargetPricesList.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Header/Notification/NotificationItem.tsx
  src/components/hooks/useLCLineChart.tsx
  src/utils/calculations.ts
  src/utils/delimiters.ts
  src/utils/excludeDelimiters.ts
  src/utils/executeIfNumeric.ts
Labels: refactor

#202 [feat] AsyncButton 구현 및 적용
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/common/Buttons/AsyncButton.tsx
  src/components/common/Buttons/Button.tsx
Labels: feat, refactor

#207 [refactor] Search Autocomplete Enter 누르면 선택 또는 이동이 되도록 수정
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/common/Buttons/IconButton.tsx
Labels: refactor

#209 [refactor] : 포트폴리오 페이지 실시간 데이터 변경에 따른 색상 변경 리팩터링
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/common/RealtimeValue.tsx
Labels: refactor

#213 [refactor] 이메일/비밀번호 계정일 때만 "계정 설정" 탭 활성화
  src/api/user/types.ts
  src/components/auth/SocialLoginButton.tsx
  src/pages/ProfilePage/ProfilePage.tsx
Labels: refactor

#214 [refactor] Header 리팩터링
  src/components/NavBar.tsx
  src/components/SearchBar/RenderOptionDefault.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownList.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListSkeleton.tsx
  src/components/common/Header/UserDropdown.tsx
  src/components/hooks/useDropdown.tsx
Labels: refactor

#217 [design] Style FallbackPage
  src/assets/icons/ic_arrow-up-right.svg
  src/assets/images/dashboard.png
  src/assets/images/landingTop.png
  src/assets/images/landingTopText.png
  src/assets/images/not_found.png
  src/assets/images/portfolio1.png
  src/assets/images/portfolio2.png
  src/assets/images/portfolio3.png
  src/assets/images/profileImage.png
  src/components/common/Icon.tsx
  src/pages/NotFoundPage.tsx
Labels: design

#219 [feat] 최근 로그인한 방식 툴팁
  src/components/Stock/StockTargetPriceForm.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/common/CustomTooltip.tsx
  src/context/UserContext.tsx
  src/pages/SignInPage/SignInForm.tsx
Labels: feat

#220 [refactor] button component 및 기타 리팩터링
  index.html
  src/components/Dashboard/PortfolioWeightPieChart/EmptyPortfolioMessage.tsx
  src/components/Portfolio/Charts/Pie/EmptyHoldingsPieChartImg.tsx
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioHolding/EmptyPortfolioHoldingTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/Portfolio/PortfolioList/EmptyPortfolioListTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Stock/StockTargetPriceForm.tsx
  src/components/Stock/TargetPriceAlertDropdown/TargetPriceAlertDropdown.tsx
  src/components/Stock/WatchlistHasStock/WatchlistHasStockDropdown.tsx
  src/components/Watchlist/NewWatchlistDialog.tsx
  src/components/Watchlist/WatchlistNameEditDialog.tsx
  src/components/Watchlist/WatchlistTable/EmptyWatchlistTable.tsx
  src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx
  src/components/Watchlist/WatchlistsTable/EmptyWatchlistsTable.tsx
  src/components/Watchlist/WatchlistsTable/WatchlistsTableToolBar.tsx
  src/components/common/Breadcrumb.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Select/Select.tsx
  src/pages/SignInPage/SignInForm.tsx
Labels: refactor

#222 [refactor] Dialog 문구 수정 및 포트폴리오 추가/수정 dialog 요청 조건 수정
  src/api/portfolio/queries/usePortfolioAddMutation.ts
  src/api/portfolio/queries/usePortfolioEditMutation.ts
  src/components/ConfirmAlert.tsx
  src/components/Notification/PortfolioNotificationList/PortfolioNotificationRow.tsx
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx
  src/components/Watchlist/WatchlistsTable/WatchlistsTableToolBar.tsx
Labels: refactor

#228 [refactor] OAuth 로그인일 때 계정 삭제 옵션 제공
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/subPages/AccountSettingsSubPage.tsx
Labels: refactor

#231 Refactor/#230 textbutton
  src/components/Notification/FeedbackCallout.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/components/common/Buttons/TextButton.tsx
  src/components/common/Header/Notification/NotificationPanel.tsx
  src/pages/ProfilePage/subPages/AccountSettingsSubPage.tsx
  src/pages/SignInPage/SignInForm.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
Labels: design, refactor

#233 [fix] PortfolioAddOrEditDialog 목표 수익률, 최대 손실율 input 계산 문제
  src/components/Portfolio/PortfolioAddOrEditDialog.tsx
  src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx
  src/components/common/toast/CustomToastContainer.tsx
  src/pages/Portfolio/PortfolioPage.tsx
Labels: bug fix, refactor

#235 #234 refactor: 포트폴리오 활성 알림 목록 정렬 순서 기준 lastUpdated -> createdAt으로 변경
  src/api/notifications/types.ts
  src/components/Notification/PortfolioNotificationList/PortfolioNotificationListTable.tsx
Labels: refactor

#238 [refactor] Account Settings Tab UI
  src/assets/images/social_login_image.svg
  src/components/common/toast/CustomToastContainer.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/subPages/AccountSettingsSubPage.tsx
  src/pages/ProfilePage/subPages/ProfileSettingsSubPage.tsx
Labels: design

#239 Refactor/#232 skeleton UI
  src/components/Dashboard/skeletons/DashboardLineChartSkeleton.tsx
  src/components/Dashboard/skeletons/DashboardOverviewSkeleton.tsx
  src/components/Dashboard/skeletons/DashboardPieChartSkeleton.tsx
  src/components/Dashboard/skeletons/PieChartSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/ChartsPanelSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/DividendBarChartSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/HoldingsPieChartSkeleton.tsx
  src/components/Portfolio/Charts/skeletons/SectorBarSkeleton.tsx
  src/components/Portfolio/MainPanelSkeleton.tsx
  src/components/Watchlist/skeletons/WatchlistsPageSkeleton.tsx
  src/components/common/PieChart/skeletons/PieChartLegendSkeleton.tsx
  src/components/common/PieChart/skeletons/PieChartSkeleton.tsx
  src/components/common/PieChart/skeletons/TallLegendSkeleton.tsx
  src/components/common/PieChart/skeletons/WideLegendSkeleton.tsx
  src/pages/Watchlist/WatchlistPage.tsx
Labels: refactor

#241 [feat] useResponsiveLayout Hook
  src/hooks/useResponsiveLayout.ts
Labels: feat

#245 [feat] 모바일 화면 기초 공사
  src/assets/icons/ic_folder.svg
  src/assets/icons/ic_kebab-vertical.svg
  src/assets/icons/ic_line-chart.svg
  src/assets/icons/ic_pie-chart.svg
  src/assets/icons/logo/ic_fineants_black.svg
  src/assets/icons/logo/ic_fineants_white.svg
  src/components/Header/Header.tsx
  src/components/Header/NavBar.tsx
  src/components/Header/desktop/HeaderTopD.tsx
  src/components/Header/mobile/HeaderTopM.tsx
  src/components/Icon.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarFixed.tsx
  src/constants/securitiesFirm.ts
  src/pages/BasePage.tsx
  src/router/router.tsx
  src/styles/designSystem.ts
Labels: design, feat

#249 [refactor] 포트폴리오 활성 알림 페이지 알림 토글 버튼 disabled 조건 추가
  src/components/Tooltips/ConditionalTooltip.tsx
  src/components/Tooltips/CustomTooltip.tsx
  src/features/auth/components/SocialLoginButton.tsx
  src/features/notification/api/types.ts
  src/features/notification/components/PortfolioNotificationList/PortfolioNotificationRow.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableHead.tsx
  src/features/portfolio/components/PortfolioOverview/PortfolioOverviewBody.tsx
  src/features/stock/components/StockTargetPriceForm.tsx
  src/mocks/data/notifications/notificationSettingsData.ts
  src/mocks/data/portfolioDetailsData.ts
  src/mocks/handlers/portfolioHandlers.ts
Labels: refactor
