Repository fine-ants/frontend, pull requests merged in 2024-07, with the labels that each got.

#333 [refactor] 종목 상세 페이지 반응형
  src/components/Drawer/BottomDrawer.tsx
  src/components/SearchBar/mobile/SearchBarM.tsx
  src/components/SelectDrawer/SelectDrawer.tsx
  src/components/TradingViewWidgets/TVStockDetailWidget.tsx
  src/features/portfolio/components/Portfolio/ChartPanel.tsx
  src/features/portfolio/components/Portfolio/mobile/MainPanelM.tsx
  src/features/portfolio/components/Portfolio/mobile/PortfolioActionDrawer.tsx
  src/features/portfolio/components/Portfolio/mobile/PortfolioHeaderM.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingSearchDrawerM.tsx
  src/features/stock/components/StockDetails.tsx
  src/features/stock/components/StockHeader.tsx
  src/features/stock/components/TargetPriceForm.tsx
  src/features/stock/components/TargetPricesList/TargetPricesList.tsx
  src/features/stock/components/TargetPricesList/errorFallback/TargetPricesListErrorFallback.tsx
  src/features/stock/components/TargetPricesList/skeleton/TargetPricesListSkeleton.tsx
  src/features/stock/components/desktop/TargetPriceAlertDropdown.tsx
  src/features/stock/components/desktop/WatchlistHasStockDropdown/WatchlistHasStockDropdown.tsx
  src/features/stock/components/desktop/WatchlistHasStockDropdown/WatchlistHasStockDropdownItem.tsx
  src/features/stock/components/desktop/WatchlistHasStockDropdown/WatchlistHasStockList.tsx
  src/features/stock/components/desktop/WatchlistHasStockDropdown/errorFallback/WatchlistHasStockListErrorFallback.tsx
  src/features/stock/components/desktop/WatchlistHasStockDropdown/skeleton/WatchlistHasStockListSkeleton.tsx
  src/features/stock/components/mobile/StockActionDrawer.tsx
  src/features/stock/components/mobile/TargetPriceAlertDialog.tsx
  src/features/stock/components/mobile/WatchlistHasStockDrawer/WatchlistHasStockDrawer.tsx
  src/features/stock/components/mobile/WatchlistHasStockDrawer/WatchlistHasStockDrawerItem.tsx
  src/features/stock/components/mobile/WatchlistHasStockDrawer/WatchlistHasStockDrawerList.tsx
  src/features/stock/components/mobile/WatchlistHasStockDrawer/skeleton/WatchlistHasStockDrawerListSkeleton.tsx
  src/features/watchlist/api/queries/useWatchlistsAddMutation.ts
  src/features/watchlist/components/dialog/mobile/WatchlistItemAddDrawerM.tsx
  src/pages/IndicesPage.tsx
  src/pages/StockPage.tsx
Labels: bug fix, design, refactor

#334 [refactor] 포트폴리오 상세 페이지 종목 반응형 및 기타 리팩터링
  src/components/CardTable/PlainCardTable/PlainCardTable.tsx
  src/components/CardTable/SelectableCardTable/SelectableCardTable.tsx
  src/components/DatePicker.tsx
  src/components/Select/Select.tsx
  src/features/notification/components/StockNotificationList/StockNotificationList.tsx
  src/features/portfolio/api/queries/usePortfolioHoldingPurchaseDeleteMutation.ts
  src/features/portfolio/api/queries/usePortfolioHoldingPurchaseEditMutation.ts
  src/features/portfolio/components/Portfolio/mobile/PortfolioHeaderM.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotAddRowD.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotRowD.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotsTableD.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingRow.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingCardBody.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingLots/PortfolioHoldingAddOrEditLots.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingLots/PortfolioHoldingLots.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingLots/PortfolioHoldingLotsCard.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingLots/PortfolioHoldingLotsTableM.tsx
  src/features/watchlist/components/WatchlistsTable/Watchlists.tsx
  src/pages/PortfolioPage.tsx
  src/pages/notifications/ActiveNotificationsPage.tsx
  src/pages/notifications/subPages/PortfolioNotificationsSubPage.tsx
  src/pages/notifications/subPages/StockNotificationsSubPage.tsx
Labels: design, refactor

#337 [refactor] z-index 리팩터링
  package-lock.json
  package.json
  src/components/BaseDialog.tsx
  src/components/Drawer/BottomDrawer.tsx
  src/components/Drawer/RightDrawer.tsx
  src/components/SelectDrawer/SelectDrawer.tsx
  src/features/notification/components/NotificationSettingsDialog/mobile/NotificationSettingsDialogM.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/PortfolioAddOrEditDialogM.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingAddDialogM.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingSearchDrawerM.tsx
  src/features/stock/components/mobile/TargetPriceAlertDialog.tsx
  src/features/watchlist/components/dialog/mobile/NewWatchlistDialogM.tsx
  src/features/watchlist/components/dialog/mobile/WatchlistItemAddDialogM.tsx
  src/features/watchlist/components/dialog/mobile/WatchlistItemAddDrawerM.tsx
  src/features/watchlist/components/dialog/mobile/WatchlistNameEditDialogM.tsx
  src/hooks/useZIndex.ts
Labels: design, feat, refactor

#341 [refactor] BottomDrawer의 DrawerItem 공통 컴포넌트
  src/components/Drawer/DrawerItem.tsx
  src/features/notification/components/NotificationPanel/mobile/NotificationPanelDrawerM.tsx
  src/features/portfolio/components/Portfolio/mobile/PortfolioActionDrawer.tsx
  src/features/stock/components/mobile/StockActionDrawer.tsx
  src/features/user/components/mobile/UserDrawer.tsx
  src/features/watchlist/components/WatchlistTable/mobile/WatchlistActionDrawer.tsx
  src/hooks/useZIndex.ts
Labels: refactor

#342 [refactor] 랜딩페이지 반응형 임시 적용
  src/assets/images/dashboardD.svg
  src/assets/images/dashboardM.svg
  src/assets/images/feature1.svg
  src/assets/images/feature2.svg
  src/assets/images/feature3.svg
  src/assets/images/feature_icon_chart.svg
  src/assets/images/feature_icon_notification.svg
  src/assets/images/feature_icon_watchlist.svg
  src/assets/images/portfolioD1.svg
  src/assets/images/portfolioD2.svg
  src/assets/images/portfolioD3.svg
  src/assets/images/portfolioM1.svg
  src/assets/images/portfolioM2.svg
  src/assets/images/portfolioM3.svg
  src/pages/LandingPage.tsx
Labels: design, refactor

#346 [refactor] useZIndex hook 문제 해결
  src/features/stock/components/mobile/StockActionDrawer.tsx
  src/features/stock/components/mobile/WatchlistHasStockDrawer/WatchlistHasStockDrawer.tsx
  src/features/watchlist/components/dialog/mobile/NewWatchlistDialogM.tsx
  src/hooks/useZIndex.ts
Labels: bug fix, refactor

#348 Refactor/#347 landing page
  src/components/Header/mobile/HeaderTopM.tsx
  src/components/NavBar/NavBarFixed.tsx
  src/constants/isPageDepthOne.ts
  src/pages/LandingPage.tsx
Labels: design, refactor

#350 [refactor: 리뷰 반영 및 isPageDepthOne 수정
  src/components/ConfirmAlert.tsx
  src/constants/isPageDepthOne.ts
Labels: refactor

#354 Refactor/#353 UI refactoring
  src/features/notification/components/EmptyNotificationList.tsx
  src/hooks/useZIndex.ts
  src/pages/auth/SignInPage.tsx
  src/pages/notifications/subPages/PortfolioNotificationsSubPage.tsx
Labels: design, refactor

#356 [refactor] 인덱스 페이지 반응형 적용
  src/components/TradingViewWidgets/TVIndicesWidget.tsx
  src/pages/IndicesPage.tsx
  src/pages/NotFoundPage.tsx
Labels: refactor
