Repository fine-ants/frontend, pull requests merged in 2024-03, with the labels that each got.

#150 [fix] Signup Page 닉네임 및 프로필 사진
  src/hooks/useNicknameDuplicateCheck.tsx
  src/pages/AuthBasePage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/EmailSubPage.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
Labels: bug fix

#151 알림 관련 리팩터링
  src/api/notifications/queries/useMemberNotificationsSettingMutation.ts
  src/api/notifications/types.ts
  src/components/Notification/FeedbackCallout.tsx
  src/components/Notification/PortfolioNotificationList/PortfolioNotificationListTable.tsx
  src/components/Notification/PortfolioNotificationList/PortfolioNotificationRow.tsx
  src/components/Notification/StockNotificationList/StockNotificationListTable.tsx
  src/components/common/Header/Notification/NotificationControl.tsx
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/mocks/data/notifications/notificationSettingsData.ts
  src/pages/ActiveNotificationsPage/subPages/PortfolioNotificationsSubPage.tsx
  src/pages/ActiveNotificationsPage/subPages/StockNotificationsSubPage.tsx
Labels: refactor

#153 [fix/refactor] Profile Settings Page
  src/api/fetcher.ts
  src/api/user/index.ts
  src/api/user/queries/useProfileDetailsMutation.ts
  src/mocks/data/userData.ts
  src/mocks/handlers/userHandlers.ts
  src/pages/ProfilePage/subPages/ProfileSettingsSubPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
Labels: bug fix, refactor

#154 비로그인 상태에 따른 액션 방어 리팩터링
  src/components/Stock/TargetPriceAlertDropdown/TargetPriceAlertDropdown.tsx
  src/components/Stock/WatchlistHasStock/WatchlistHasStockDropdown.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx
Labels: refactor

#159 [fix/refactor] TODO 정리하며 필요한 부분 리팩터링
  package-lock.json
  package.json
  src/api/notifications/queries/useStockTargetPriceAddMutation.tsx
  src/api/notifications/types.ts
  src/components/AccountDeleteDialog.tsx
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Stock/StockTargetPriceForm.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Header/Notification/NotificationItem.tsx
  src/components/common/IconCalendar.tsx
  src/components/common/Legend/WideLegend.tsx
  src/components/common/Legend/WideLegendItem.tsx
  src/components/common/SubPageNav/SubPageNav.tsx
  src/components/common/TextField/BaseTextField.tsx
  src/components/common/toast/CustomToastContainer.tsx
  src/mocks/data/notifications/memberNotificationsData.ts
  src/pages/ProfilePage/subPages/AccountSettingsSubPage.tsx
  src/pages/ProfilePage/subPages/ProfileSettingsSubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
  src/pages/StockPage.tsx
  svg.d.ts
  vite.config.ts
Labels: bug fix, refactor

#162 [fix] UI fixes
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/pages/Portfolio/PortfolioPage.tsx
  src/pages/Watchlist/WatchlistsPage.tsx
Labels: bug fix, design

#163 [feat] 공용 컴포넌트 TextButton, IconButton 구현
  src/api/stock/index.ts
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/IconButton.tsx
  src/components/common/Buttons/TextButton.tsx
  src/components/common/Buttons/types.ts
  src/components/common/Header/Header.tsx
  src/components/common/Icon.tsx
  src/styles/designSystem.ts
Labels: feat

#166 #157 fix: 배포시 fcm service worker 미작동 버그 수정 (임시 해결)
  README.md
  config/vitePlugins.ts
  src/firebase-messaging-sw.js
  tsconfig.json
  vite.config.ts
Labels: bug fix

#167 [merge] FCM Service Worker 배포 시 미작동 임시 해결
  config/vitePlugins.ts
  src/firebase-messaging-sw.js
  tsconfig.json
  vite.config.ts
Labels: merge

#168 [deploy] FCM Service Worker 배포 시 미작동 임시 해결
  config/vitePlugins.ts
  src/firebase-messaging-sw.js
  tsconfig.json
  vite.config.ts
Labels: deploy

#174 [migrate] @fineants/demoltion v1.1.13 적용
  package-lock.json
  package.json
  src/components/common/Header/Notification/NotificationItem.tsx
  src/components/common/Header/Notification/NotificationSettingsDialog.tsx
  src/components/hooks/useLCLineChart.tsx
  src/utils/formatTickValue.ts
  src/utils/getElapsedSince.ts
  src/utils/retryFn.ts
Labels: migration
