Repository fine-ants/frontend, pull requests merged in 2024-01, with the labels that each got.

#81 [feat] 포트폴리오 상세페이지 리팩터링
  index.html
  public/favicon-dark.ico
  public/favicon-light.ico
  src/api/portfolio/types.ts
  src/api/watchlist/index.ts
  src/assets/icons/ic_calendar.svg
  src/assets/icons/ic_chevron-down.svg
  src/assets/icons/logo/ic_fineants.svg
  src/components/Portfolio/Charts/ChartsPanel.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarChart.tsx
  src/components/Portfolio/Charts/errorFallback/ChartsPanelErrorFallback.tsx
  src/components/Portfolio/MainPanel.tsx
  src/components/Portfolio/MainPanelSkeleton.tsx
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/IconCalendar.tsx
  src/components/Portfolio/PortfolioHoldings/PorfolioHoldingTableHead.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingPurchaseAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Portfolio/errorFallback/MainPanelErrorFallback.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Select/Select.tsx
  src/constants/securitiesFirm.ts
  src/mocks/handlers/watchlistHandlers.ts
  src/pages/Portfolio/PortfolioPage.tsx
  src/router/router.tsx
  src/styles/securitiesFirmLogos.ts
Labels: design, feat, refactor

#84 signinloadingpage UI
  src/pages/SignInLoadingPage.tsx
Labels: design, feat

#85 [feat] StockPage 구현
  src/api/portfolio/types.ts
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/Portfolio/errorFallback/MainPanelErrorFallback.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/TradingViewWidgets/TVStockDetailWidget.tsx
  src/components/TradingViewWidgets/TVTickerTape.tsx
  src/components/Watchlist/WatchlistTableRow.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Legend/WideLegend.tsx
  src/mocks/data/portfolioDetailsData.ts
  src/mocks/handlers/portfolioHandlers.ts
  src/pages/Portfolio/PortfolioPage.tsx
  src/pages/StockPage.tsx
  src/styles/GlobalStyles.tsx
  src/styles/designSystem.ts
Labels: design, feat, refactor

#87 [deploy] 배포
  src/components/Portfolio/Charts/ChartsPanel.tsx
  src/components/Portfolio/MainPanel.tsx
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/pages/Portfolio/PortfolioPage.tsx
  src/router/Routes.ts
Labels: bug fix, merge

#88 [deploy] 배포
  src/components/common/Icon.tsx
Labels: bug fix, merge

#89 [refactor] Porfolios Dropdown 및 SearchBar
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/components/NavBar.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarChartContainer.tsx
  src/components/Portfolio/Charts/Pie/HoldingsPieChart.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/SearchBar/RenderOptionDefault.tsx
  src/components/SearchBar/RenderOptionSelect.tsx
  src/components/SearchBar/RenderOptionSelectMultiple.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/Watchlist/WatchlistTableRow.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/PortfoliosDropdown.tsx
  src/components/hooks/useDropdown.tsx
  src/components/hooks/useLCLineChart.tsx
  src/utils/delimiters.ts
  src/utils/removeWord.ts
  src/utils/thousandsDelimiter.ts
  tsconfig.json
Labels: design, refactor

#93 [fix] SSE 연결 문제 해결
  src/api/hooks/useSSE.tsx
  src/main.tsx
  src/pages/Portfolio/PortfolioPage.tsx
Labels: bug fix, refactor

#95 refresh token 만료시 error 무한 루프 해결
  src/api/fetcher.ts
Labels: bug fix

#99 portfolio add dialog 리팩터링
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/common/Icon.tsx
  src/components/common/Select/Select.tsx
  src/styles/GlobalStyles.tsx
Labels: refactor

#100 [refactor] Table 공통 Component 구현
  src/api/fetcher.ts
  src/api/portfolio/index.ts
  src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioListTableQuery.ts
  src/components/Portfolio/MainPanel.tsx
  src/components/Portfolio/PortfolioHolding/EmptyPortfolioHoldingTable.tsx
  src/components/Portfolio/PortfolioHolding/PorfolioHoldingTableHead.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableBody.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingPurchaseAddDialog.tsx
  src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableHead.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/IconCalendar.tsx
  src/components/common/Table/Table.tsx
  src/components/common/Table/utils.ts
  src/styles/GlobalStyles.tsx
Labels: refactor

#104 [feat] Header User Dropdown UI 구현
  src/assets/icons/ic_user.svg
  src/components/common/Header/Header.tsx
  src/components/common/Header/PortfoliosDropdown.tsx
  src/components/common/Header/UserControls.tsx
  src/components/common/Header/UserDropdown.tsx
  src/components/common/Icon.tsx
  src/components/hooks/useDropdown.tsx
  src/router/ProtectedRoute.tsx
Labels: design, feat

#105 [merge] User Profile Dropdown
  src/assets/icons/ic_user.svg
  src/components/common/Header/Header.tsx
  src/components/common/Header/PortfoliosDropdown.tsx
  src/components/common/Header/UserControls.tsx
  src/components/common/Header/UserDropdown.tsx
  src/components/common/Icon.tsx
  src/components/hooks/useDropdown.tsx
  src/router/ProtectedRoute.tsx
Labels: merge

#109 QA 포트폴리오 관련 리팩터링
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PorfolioHoldingTableHead.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableHead.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableBody.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/common/Header/PortfoliosDropdown.tsx
Labels: refactor

#110 [migrate] MSW 2.1.1
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/portfolio/types.ts
  src/main.tsx
  src/mocks/browserServiceWorker.ts
  src/mocks/data/stockData.ts
  src/mocks/data/watchlistData.ts
  src/mocks/handlers/authHandlers.ts
  src/mocks/handlers/dashboardHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/portfolioHandlers.ts
  src/mocks/handlers/stockHandlers.ts
  src/mocks/handlers/watchlistHandlers.ts
  tsconfig.json
  vite.config.ts
Labels: migration

#114 toast alert design
  src/assets/icons/ic_info.svg
  src/assets/icons/ic_warning.svg
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/VerificationCodeInput/VerificationCodeInput.tsx
  src/components/common/Badges/CounterBadge.tsx
  src/components/common/Badges/RateBadge.tsx
  src/components/common/Icon.tsx
  src/components/common/TextField/BaseTextField.tsx
  src/components/common/TextField/ErrorText.tsx
  src/components/common/toast/CustomToastCloseButton.tsx
  src/components/common/toast/CustomToastContainer.tsx
  src/components/common/toast/CustomToastIcon.tsx
  src/components/common/toast/createToast.ts
  src/components/common/toast/createToast.tsx
  src/pages/SignInPage/SignInForm.tsx
  src/styles/designSystem.ts
Labels: design

#115 [refactor] PortfoliosDropdown Relayout 방지 및 기타 수정
  src/api/portfolio/queries/queryKeys.ts
  src/api/portfolio/queries/usePortfolioAddMutation.ts
  src/api/portfolio/queries/usePortfolioDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioEditMutation.ts
  src/api/portfolio/queries/usePortfolioListHeaderQuery.ts
  src/api/portfolio/queries/usePortfolioListQuery.ts
  src/api/portfolio/queries/usePortfolioListTableQuery.ts
  src/api/portfolio/queries/usePortfoliosDeleteMutation.ts
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTable.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownList.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListErrorFallback.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListSkeleton.tsx
  src/components/common/Icon.tsx
  src/components/hooks/useDropdown.tsx
  src/mocks/data/portfolioData.ts
  src/mocks/handlers/portfolioHandlers.ts
Labels: refactor

#117 [bug] 바뀐 Design System이 미적용된 부분 수정
  src/components/ConfirmAlert.tsx
  src/components/Dashboard/DashboardOverview.tsx
  src/components/Dashboard/DashboardPortfolioWeight.tsx
  src/components/Dashboard/DashboardTotalValuationTrend.tsx
  src/components/Dashboard/PortfolioWeightPieChart/EmptyPortfolioMessage.tsx
  src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/components/Portfolio/Charts/Dividend/DividendBarTooltip.tsx
  src/components/Portfolio/Charts/skeletons/ChartsPanelSkeleton.tsx
  src/components/Portfolio/PortfolioAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/EmptyPortfolioHoldingTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableHead.tsx
  src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/components/Portfolio/PortfolioList/EmptyPortfolioListTable.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableHead.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx
  src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx
  src/components/Portfolio/PortfolioOverview.tsx
  src/components/VerificationCodeInput/VerificationCodeInput.tsx
  src/components/Watchlist/WatchlistAddDialog.tsx
  src/components/Watchlist/WatchlistItemAddDialog.tsx
  src/components/Watchlist/WatchlistTable/EmptyWatchlistTable.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableHead.tsx
  src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
  src/components/Watchlist/WatchlistsTable/EmptyWatchlistsTable.tsx
  src/components/Watchlist/WatchlistsTable/WatchlistsTableHead.tsx
  src/components/Watchlist/WatchlistsTable/WatchlistsTableRow.tsx
  src/components/auth/AuthPageCommon.tsx
  src/components/auth/SocialLoginButton.tsx
  src/components/common/Breadcrumb.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/CustomTooltip.tsx
  src/components/common/Footer.tsx
  src/components/common/Header/UserDropdown.tsx
  src/components/common/Legend/TallLegend.tsx
  src/components/common/Legend/TallLegendItem.tsx
  src/components/common/Legend/WideLegend.tsx
  src/components/common/Legend/WideLegendItem.tsx
  src/components/common/Pagination/TablePagination.tsx
  src/components/common/Select/Select.tsx
  src/components/common/Tab.tsx
  src/components/common/TextField/BaseTextField.tsx
  src/components/common/TextField/ErrorText.tsx
  src/components/hooks/useLCLineChart.tsx
  src/pages/IndicesPage.tsx
  src/pages/LandingPage.tsx
  src/pages/SignInPage/SignInForm.tsx
  src/pages/SignUpPage/ProgressBoard/Progress.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/subPages/MainSubPage.tsx
  src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
  src/pages/SignUpPage/subPages/VerificationSubPage.tsx
  src/pages/StockPage.tsx
Labels: bug fix

#121 toast alert 가운데로 위치 변경
  src/components/common/toast/CustomToastContainer.tsx
  src/components/common/toast/createToast.tsx
Labels: refactor

#123 [feat] 프로필/계정 설정 Page
  package-lock.json
  package.json
  src/api/auth/queries/queryKeys.ts
  src/api/auth/queries/useSignInMutation.ts
  src/api/auth/queries/useSignUpMutation.ts
  src/api/hooks/useSSE.tsx
  src/api/portfolio/queries/usePortfolioAddMutation.ts
  src/api/portfolio/queries/usePortfolioDeleteMutation.ts
  src/api/portfolio/queries/usePortfolioEditMutation.ts
  src/api/portfolio/queries/usePortfoliosDeleteMutation.ts
  src/api/settings/index.ts
  src/api/settings/queries/queryKeys.ts
  src/api/settings/queries/useAccountDeleteMutation.ts
  src/api/settings/queries/usePasswordEditMutation.ts
  src/api/settings/queries/useProfileDetailsMutation.ts
  src/assets/icons/ic_refresh.svg
  src/components/AccountDeleteDialog.tsx
  src/components/SearchBar/RenderOptionDefault.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListErrorFallback.tsx
  src/components/common/Header/UserDropdown.tsx
  src/components/common/Icon.tsx
  src/components/common/TextField/ErrorText.tsx
  src/components/common/TextField/PasswordTextField.tsx
  src/components/common/TextField/TextField.tsx
  src/context/UserContext.tsx
  src/hooks/useNicknameDuplicateCheck.tsx
  src/main.tsx
  src/mocks/data/settingsData.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/settingsHandlers.ts
  src/pages/MyProfilePage.tsx
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/subPages/AccountSettingsSubPage.tsx
  src/pages/SettingsPage/subPages/ProfileSettingsSubPage.tsx
  src/pages/SignInPage/SignInForm.tsx
  src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: design, feat
