Repository fine-ants/frontend, pull requests merged in 2024-06, with the labels that each got.

#310 [refactor] Portfolio add/edit dialog 및 PortfolioList table 반응형
  src/components/CardTable/SelectableCardTable/SelectableCard.tsx
  src/components/CardTable/SelectableCardTable/SelectableCardTable.tsx
  src/components/CardTable/SelectableCardTable/SelectableCardTableToolbar.tsx
  src/components/Drawer/BottomDrawer.tsx
  src/components/Select/Select.tsx
  src/components/SelectDrawer/SelectDrawer.tsx
  src/components/SelectDrawer/SelectDrawerOption.tsx
  src/components/SlideUpTransition.tsx
  src/features/notification/components/NotificationPanel/mobile/NotificationPanelDrawerM.tsx
  src/features/notification/components/NotificationSettingsDialog/NotificationSettingsContent.tsx
  src/features/notification/components/NotificationSettingsDialog/NotificationSettingsHeader.tsx
  src/features/notification/components/NotificationSettingsDialog/desktop/NotificationSettingsDialogD.tsx
  src/features/notification/components/NotificationSettingsDialog/mobile/NotificationSettingsDialogM.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/PortfolioAddOrEditDialog.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/desktop/PortfolioAddOrEditDialogD.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/PortfolioAddOrEditDialogM.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/SecuritiesFirmSelectDrawer.tsx
  src/features/portfolio/components/PortfolioList/EmptyPortfolioList.tsx
  src/features/portfolio/components/PortfolioList/PortfolioList.tsx
  src/features/portfolio/components/PortfolioList/PortfolioListDeleteConfirm.tsx
  src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableToolBar.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardBody.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardTable.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardTableToolbar.tsx
  src/features/user/components/mobile/UserDrawer.tsx
  src/pages/BasePage.tsx
  src/pages/PortfolioListPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/pages/profile/subPages/ProfileSettingsSubPage.tsx
Labels: refactor

#312 [release] 6월 1주차 배포 테스트
  src/components/CardTable/OrderByDrawer/MainContent.tsx
  src/components/CardTable/OrderByDrawer/OrderByContent.tsx
  src/components/CardTable/OrderByDrawer/OrderByDrawer.tsx
  src/components/CardTable/OrderByDrawer/OrderContent.tsx
  src/components/CardTable/OrderByDrawer/types.ts
  src/components/CardTable/SelectableCardTable/SelectableCard.tsx
  src/components/CardTable/SelectableCardTable/SelectableCardTable.tsx
  src/components/CardTable/SelectableCardTable/SelectableCardTableToolbar.tsx
  src/components/Drawer/BottomDrawer.tsx
  src/components/Select/Select.tsx
  src/components/SelectDrawer/SelectDrawer.tsx
  src/components/SelectDrawer/SelectDrawerOption.tsx
  src/components/SlideUpTransition.tsx
  src/features/notification/components/NotificationPanel/mobile/NotificationPanelDrawerM.tsx
  src/features/notification/components/NotificationSettingsDialog/NotificationSettingsContent.tsx
  src/features/notification/components/NotificationSettingsDialog/NotificationSettingsHeader.tsx
  src/features/notification/components/NotificationSettingsDialog/desktop/NotificationSettingsDialogD.tsx
  src/features/notification/components/NotificationSettingsDialog/mobile/NotificationSettingsDialogM.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/PortfolioAddOrEditDialog.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/desktop/PortfolioAddOrEditDialogD.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/PortfolioAddOrEditDialogM.tsx
  src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/SecuritiesFirmSelectDrawer.tsx
  src/features/portfolio/components/PortfolioList/EmptyPortfolioList.tsx
  src/features/portfolio/components/PortfolioList/PortfolioList.tsx
  src/features/portfolio/components/PortfolioList/PortfolioListDeleteConfirm.tsx
  src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableToolBar.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardBody.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardTable.tsx
  src/features/portfolio/components/PortfolioList/mobile/PortfolioListCardTableToolbar.tsx
  src/features/user/components/mobile/UserDrawer.tsx
  src/pages/BasePage.tsx
  src/pages/PortfolioListPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/pages/profile/subPages/ProfileSettingsSubPage.tsx
Labels: release

#313 [refactor] 인증 방식 cookie로 변경
  package-lock.json
  package.json
  src/api/fetcher.ts
  src/features/auth/api/index.ts
  src/features/auth/api/queries/useOAuthSignInMutation.ts
  src/features/auth/api/queries/useSignInMutation.ts
  src/features/portfolio/hooks/useSSE.ts
  src/features/stock/api/index.ts
  src/features/user/api/index.ts
  src/features/user/context/UserContext.tsx
  vite.config.ts
Labels: refactor

#318 [refactor] OAuth 절차 변경
  src/features/auth/api/index.ts
  src/features/auth/api/queries/useOAuthSignInMutation.ts
  src/features/auth/components/SignInForm.tsx
  src/features/auth/components/SocialLoginButton.tsx
  src/features/user/context/UserContext.tsx
  src/pages/auth/OAuthLoadingPage.tsx
  src/router/router.tsx
Labels: refactor

#320 [refactor] 이미지 번들 사이즈 줄임 및 기타 최적화
  src/assets/images/landingTop.png
  src/assets/images/landingTop.svg
  src/components/Buttons/IconButton.tsx
  src/components/Footer.tsx
  src/components/Header/desktop/HeaderTopD.tsx
  src/components/Header/mobile/HeaderTopM.tsx
  src/components/Select/Select.tsx
  src/features/dashboard/components/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/features/notification/components/NotificationControl/ControlButton.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingRow.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableBody.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableHead.tsx
  src/features/portfolio/components/PortfolioOverview/PortfolioOverviewBody.tsx
  src/features/user/components/UserProfileButton.tsx
  src/pages/LandingPage.tsx
Labels: refactor

#322 [refactor] IOS PWA UI 및 기타 리팩터링
  index.html
  src/components/NavBar/NavBar.tsx
  src/components/TextField/PasswordTextField.tsx
  src/components/TextField/TextField.tsx
  src/features/auth/components/SignInForm.tsx
  src/pages/auth/signup/subPages/EmailSubPage.tsx
Labels: refactor

#323 [release] 6월 3주차 배포 테스트 release
  index.html
  src/assets/images/landingTop.png
  src/assets/images/landingTop.svg
  src/components/Buttons/IconButton.tsx
  src/components/Footer.tsx
  src/components/Header/desktop/HeaderTopD.tsx
  src/components/Header/mobile/HeaderTopM.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Select/Select.tsx
  src/components/TextField/PasswordTextField.tsx
  src/components/TextField/TextField.tsx
  src/features/auth/api/index.ts
  src/features/auth/api/queries/useOAuthSignInMutation.ts
  src/features/auth/components/SignInForm.tsx
  src/features/auth/components/SocialLoginButton.tsx
  src/features/dashboard/components/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx
  src/features/notification/components/NotificationControl/ControlButton.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingRow.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableBody.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableHead.tsx
  src/features/portfolio/components/PortfolioOverview/PortfolioOverviewBody.tsx
  src/features/user/components/UserProfileButton.tsx
  src/features/user/context/UserContext.tsx
  src/pages/LandingPage.tsx
  src/pages/auth/OAuthLoadingPage.tsx
  src/pages/auth/signup/subPages/EmailSubPage.tsx
  src/router/router.tsx
Labels: release

#326 [bug] 기타 UI 버그 해결
  src/components/Badges/RateBadge.tsx
  src/components/Table/CollapsibleSelectableTable.tsx
  src/components/Table/CollapsibleTable.tsx
  src/components/Table/PlainTable.tsx
  src/components/Table/SelectableTable.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingRow.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableToolBar.tsx
  src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableHead.tsx
  src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableRow.tsx
  src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableToolBar.tsx
  src/features/watchlist/components/WatchlistTable/WatchlistTableToolBar.tsx
  src/features/watchlist/components/WatchlistsTable/WatchlistsTableToolBar.tsx
  src/mocks/data/portfolioData.ts
  src/mocks/handlers/portfolioHandlers.ts
Labels: bug fix, design

#327 [refactor] 포트폴리오 상세 페이지 반응형 추가
  package-lock.json
  package.json
  src/components/DatePicker.tsx
  src/components/Drawer/BottomDrawer.tsx
  src/components/Drawer/RightDrawer.tsx
  src/components/Footer.tsx
  src/components/SearchBar/mobile/SearchBarM.tsx
  src/components/SelectDrawer/SelectDrawer.tsx
  src/constants/styleConstants.ts
  src/features/portfolio/api/types.ts
  src/features/portfolio/components/Charts/ChartsPanel.tsx
  src/features/portfolio/components/Charts/Dividend/DividendBarChart.tsx
  src/features/portfolio/components/Charts/Dividend/DividendBarChartContainer.tsx
  src/features/portfolio/components/Charts/PieChart/PieChartContainer.tsx
  src/features/portfolio/components/Charts/Sector/SectorBar.tsx
  src/features/portfolio/components/Charts/Sector/SectorBarChartContainer.tsx
  src/features/portfolio/components/Portfolio/ChartPanel.tsx
  src/features/portfolio/components/Portfolio/MainPanel.tsx
  src/features/portfolio/components/Portfolio/desktop/MainPanelD.tsx
  src/features/portfolio/components/Portfolio/mobile/MainPanelM.tsx
  src/features/portfolio/components/Portfolio/skeletons/ChartsPanelSkeleton.tsx
  src/features/portfolio/components/Portfolio/skeletons/MainPanelSkeleton.tsx
  src/features/portfolio/components/PortfolioHeaderDrawer.tsx
  src/features/portfolio/components/PortfolioHeaderM.tsx
  src/features/portfolio/components/PortfolioHolding/EmptyPortfolioHoldingTable.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingAddDialog.tsx
  src/features/portfolio/components/PortfolioHolding/PortfolioHoldingDeleteConfirm.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingAddDialogD.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingRow.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingTable.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingTableBody.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingTableHead.tsx
  src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingTableToolBar.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingAddDialogM.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingCardBody.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingCardTable.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingCardTableToolbar.tsx
  src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingSearchDrawerM.tsx
  src/features/portfolio/components/PortfolioOverview/desktop/PortfolioOverviewBodyD.tsx
  src/features/portfolio/components/PortfolioOverview/desktop/PortfolioOverviewD.tsx
  src/features/portfolio/components/PortfolioOverview/mobile/PortfolioOverviewM.tsx
  src/features/portfolio/components/types.ts
  src/features/stock/components/StockSearchPanel/mobile/StockSearchPanel.tsx
  src/mocks/data/portfolioData.ts
  src/pages/PortfolioPage.tsx
Labels: refactor
